spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=SmartUni;encrypt=true;trustServerCertificate=true;loginTimeout=30
spring.datasource.username=springuser
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=smartunipro-secret-key-2026-must-be-at-least-32-characters-long
jwt.expiration=86400000

ai.service.url=https://multiply-devotee-crablike.ngrok-free.dev

server.port=8080